# wrangler.toml

name = "gmessages-api"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]

d1_databases = [
    { binding = "DB", database_name = "gmessages-db-prod", database_id = "1b323ed8-3234-4228-b8ba-f77694c2a2c8" }
]

[observability.logs]
enabled = true

[env.dev]
name = "gmessages-api-dev"
d1_databases = [
    { binding = "DB", database_name = "gmessages-db-dev", database_id = "4253c6db-0254-4ea0-b331-74b01736eac7" }
]
